apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nominatim.fullname" . }}-apache-configmap
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/000-default.conf").AsConfig | indent 2 }}